# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [2]:
# your code here
import numpy as np

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [18]:
# your code here
a = np.array([[1, 1, 1], [1, 1, 1]])
b = np.array([[1, 1, 1], [1, 1, 1]])

np.add(a,b)



array([[2, 2, 2],
       [2, 2, 2]])

Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [28]:
# your code here
c = np.array([[1, 1], [1, 1], [1, 1]])
print (c)

# no, because of different shape

[[1 1]
 [1 1]
 [1 1]]


Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [31]:
# your code here
c = np.array([[1, 1], [1, 1], [1, 1]])
d= np.reshape (c, (2, 3))
print (d)
# yes, a and d can now be added because they have the same shape

[[1 1 1]
 [1 1 1]]


Which combination of arrays are you able to multiply with each other? Why?

In [32]:
# your code here
#Multiplication of two matrices X and Y is defined only if the number of columns in X is equal to the number of rows Y . If X is a n x m matrix and Y is a m x l matrix then, XY is defined and has the dimension n x l (but YX is not defined).

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [39]:
# your code here
list=list(range(0, 11))
np.square(list)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [50]:
# your code here
a=np.random.random(1)*100
print(a)

[62.29644736]
