# The Numpy Package

#### Importing and working with the package

In [1]:
import numpy

In [2]:
numpy?

In [3]:
import numpy as np


#### Numpy data structures: arrays

In [4]:
a = np.random.random((2, 3, 5))

In [5]:
print(a)

[[[0.79642255 0.0625815  0.78559279 0.58242777 0.62857479]
  [0.79374187 0.57695413 0.06976741 0.98711701 0.71975122]
  [0.91921278 0.10179167 0.45506771 0.79003264 0.90543033]]

 [[0.63745677 0.53068325 0.36107278 0.86813587 0.10388631]
  [0.50749507 0.7342635  0.56228428 0.91631653 0.69827784]
  [0.48545258 0.49125807 0.49596689 0.82018592 0.95896381]]]


In [6]:
print(a.shape)
print(a.size)

(2, 3, 5)
30


#### Extracting data from arrays

In [57]:
a[0,0,0]
a[0,:,2]

array([0.00123844, 0.46484724, 0.76578421])

In [7]:
# numpy arrays are mutable!
a[0,0,0] = 5
a

array([[[5.        , 0.0625815 , 0.78559279, 0.58242777, 0.62857479],
        [0.79374187, 0.57695413, 0.06976741, 0.98711701, 0.71975122],
        [0.91921278, 0.10179167, 0.45506771, 0.79003264, 0.90543033]],

       [[0.63745677, 0.53068325, 0.36107278, 0.86813587, 0.10388631],
        [0.50749507, 0.7342635 , 0.56228428, 0.91631653, 0.69827784],
        [0.48545258, 0.49125807, 0.49596689, 0.82018592, 0.95896381]]])

#### Converting other data structures to arrays

In [8]:
mylist1 = ['cat', 'dog']
mylist2 = [['cat', 'dog'], ['squirrel', 'mouse'], ['anteater', 'bear']]

In [9]:
np.array(mylist1)

array(['cat', 'dog'], dtype='<U3')

In [10]:
np.array(mylist2)

array([['cat', 'dog'],
       ['squirrel', 'mouse'],
       ['anteater', 'bear']], dtype='<U8')

In [17]:
test = [4, 5, 6, 7, 8, 2, 4, 5, 6]
np.array(test + mylist1)

array(['4', '5', '6', '7', '8', '2', '4', '5', '6', 'cat', 'dog'],
      dtype='<U11')

#### Element-wise mathematical operations

In [14]:
first = np.random.random((3, 4))
second = np.random.random((3, 4))
print(first)
print(second)

[[0.0783523  0.95060236 0.09750483 0.83566456]
 [0.90040164 0.15677193 0.07002215 0.87279178]
 [0.98060731 0.99013369 0.44011304 0.55425739]]
[[0.82904426 0.69583158 0.2904576  0.93152859]
 [0.52375315 0.06678461 0.76752447 0.95009981]
 [0.90886286 0.87815701 0.76152044 0.95154151]]


In [15]:
result = np.add(first, second)
print(result)

[[0.90739656 1.64643395 0.38796244 1.76719315]
 [1.42415479 0.22355654 0.83754662 1.82289159]
 [1.88947017 1.8682907  1.20163348 1.50579889]]


In [16]:
first + second

array([[0.90739656, 1.64643395, 0.38796244, 1.76719315],
       [1.42415479, 0.22355654, 0.83754662, 1.82289159],
       [1.88947017, 1.8682907 , 1.20163348, 1.50579889]])

In [66]:
[1, 2, 4] + [1, 2, 3]

[1, 2, 4, 1, 2, 3]

In [67]:
np.add([1, 2, 4], [1, 2, 3])

array([2, 4, 7])